# Generated by Django 4.2.7 on 2023-12-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50, verbose_name='Name')),
                ('species', models.TextField(max_length=15, verbose_name='Species')),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
    ]
