# Generated by Django 4.2.7 on 2023-12-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("StarWars", "0003_movie_charactermovie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermovie",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                related_query_name="character",
                to="StarWars.character",
            ),
        ),
        migrations.AlterField(
            model_name="charactermovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                related_query_name="movie",
                to="StarWars.movie",
            ),
        ),
    ]
