# Generated by Django 4.2.7 on 2023-12-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StarWars", "0004_alter_charactermovie_character_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="episode",
            field=models.IntegerField(null=True, verbose_name="Episode"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(null=True, verbose_name="Release Year"),
        ),
    ]
